### ISSUE TITLE
After install exception for View Str:: not found

### ISSUE THREAD

**Issue by KinG-InFeT** [arukompas/better-log-viewer#10]
Go to http://127.0.0.1:8001/log-viewer
Out error
```
Class 'Str' not found (View: /home/vluongo/workspace/*****/vendor/arukompas/better-log-viewer/src/resources/views/logs/index.blade.php)
```

**Comment by KinG-InFeT** [comment]
@arukompas please merge fix into master

**Comment by arukompas** [comment]
@KinG-InFeT - hey, thanks for the report! Fixed in https://github.com/arukompas/better-log-viewer/commit/58e0381b574754cb437afc330a2360b757d38970
