### ISSUE TITLE
Laravel 8 support

### ISSUE THREAD

**Issue by leslieeilsel** [arukompas/better-log-viewer#11]
Is there a timeline to support Laravel 8?

**Comment by arukompas** [comment]
@leslieeilsel - hey! Thanks for the interest, I'll do it this weekend and let you know :)

**Comment by arukompas** [comment]
@leslieeilsel - hey, thanks for your patience. The latest version is now compatible with Laravel 8!

**Comment by KinG-InFeT** [comment]
please, update the package and readme file :D

**Comment by KinG-InFeT** [comment]
https://github.com/arukompas/better-log-viewer/pull/12

**Comment by arukompas** [comment]
Much appreciated @KinG-InFeT , thank you! 😄
